site_name: Starless Sky
site_description: A website for information about the world of Starless Sky
site_author: Matt
site_url: https://matt4c6f656872.github.io/Starless-Sky/
nav:
  - Welcome: index.md # needs to be called index
  - The World:
      - the-world/index.md
      - Wahda: the-world/wahda/index.md
          - Locations:
              - locations/index.md
              - Wahda: locations/wahda.md
              - Alhir-Alhar: locations/alhir-alhar.md
              - Temple of the Sun: locations/temple-of-the-sun.md
              - Brin's Forest: locations/brins-forest.md
      - Badlands:
          - the-world/badlands/index.md
          - Locations:
              - locations/index.md
              - Mika: locations/mika.md
      - Shadowed Lands:
          - the-world/shadowed-lands/index.md
          - Locations:
              - locations/index.md
              - Castle: locations/castle.md
      - The Lost Mountains:
          - the-world/lost-mountains/index.md
          - Locations:
              - locations/index.md
              - The Five Pillars: locations/five-pillars/index.md
      - Gahere-Rere: docs/the-world/gahere-rere/index.md
  - The Sun:
      - the-sun/index.md
  - The Moon:
      - the-moon/index.md
  - Religion:
      - religion/index.md 
      - Gods: religion/gods.md
      - Saints: religion/saints.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.top
    - content.code.annotate
    - navigation.indexes
    # In order to link a page to a section, create a new document with the name index.md in the respective folder, and add it to the beginning of your navigation section.

  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Extensions
markdown_extensions:
  - footnotes
  # - attr_list
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true

plugins:
  - search
  - roamlinks
  - blog
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js
