site_name: Starless Sky
site_description: A website for information about the world of Starless Sky
site_author: Matt
site_url: https://matt4c6f656872.github.io/Starless-Sky/

nav:
  - Welcome: index.md
  - The World:
    - Overview: the-world/index.md
    - Wahda:
      - Overview: the-world/wahda/index.md
      - Locations:
        - Wahda: the-world/wahda/locations/wahda.md
        - Alhir-Alhar: the-world/wahda/locations/alhir-alhar.md
        - Temple of the Sun: the-world/wahda/locations/temple-of-the-sun.md
        - Brin's Forest: the-world/wahda/locations/brins-forest.md
        - TeWhanga: the-world/wahda/locations/tewhanga.md
    - Badlands:
      - Overview: the-world/badlands/index.md
      - Locations:
        - Mika: the-world/badlands/locations/mika.md
        - Ancient Ruins: the-world/badlands/locations/ancient-ruins.md
    - Shadowed Lands:
      - Overview: the-world/shadowed-lands/index.md
    - The Lost Mountains:
      - Overview: the-world/the-lost-mountains/index.md
      - Locations:
        - The Nine Pillars: the-world/the-lost-mountains/locations/the-nine-pillars.md
    - Gahere-Rere:
      - Overview: the-world/gahere-rere/index.md
      - Locations:
        - Gahere-Rere Locations: the-world/gahere-rere/locations/index.md
  - The Sun:
    - Overview: the-sun/index.md
  - The Moon:
    - Overview: the-moon/index.md
  - Religion:
    - Overview: religion/index.md
    - Gods:
      - Akadi: religion/gods/akadi.md
      - Grumma: religion/gods/grumma.md
      - Ossu: religion/gods/ossu.md
      - Shia: religion/gods/shia.md
      - The Black Sky: religion/gods/the-black-sky.md
    - Saints:
      - The Flower of the North: religion/saints/the-flower-of-the-north.md
      - The Dead Watcher: religion/saints/the-dead-watcher.md
      - The Firekeeper: religion/saints/the-firekeeper.md
      - Hundred Sands: religion/saints/hundred-sands.md
      - The Living Memory: religion/saints/the-living-memory.md
      - The Mad Witch of the West: religion/saints/the-mad-witch-of-the-west.md
      - The Muse of Mires: religion/saints/the-muse-of-mires.md
      - The Nightmare Hunter: religion/saints/the-nightmare-hunter.md
      - The Raindancer: religion/saints/the-raindancer.md
      - The Relic: religion/saints/the-relic.md
      - The Saint of Storms: religion/saints/the-saint-of-storms.md
      - The Sivv: religion/saints/the-sivv.md
      - The Smallfolk King: religion/saints/the-smallfolk-king.md
      - The Sunforged: religion/saints/the-sunforged.md
      - He Whose Steps Loosens Stones: religion/saints/he-whose-steps-loosens-stones.md
      - She Who Watches the Sky: religion/saints/she-who-watches-the-sky.md
      - They Who Walk the Paths: religion/saints/they-who-walk-the-paths.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.top
    - content.code.annotate
    - navigation.indexes

  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Extensions
markdown_extensions:
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true

plugins:
  - search
  - roamlinks
  - blog
  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js
